apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uctpg97da-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uctpg97da-nodejs 
  name: uctpg97da-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: uctpg97da-nodejs 
